#springdoc:
#  swagger-ui:
#    urls:
#      # Les URLs seront configurées dynamiquement
#    disable-swagger-default-url: true
#  api-docs:
#    enabled: true


#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    disable-swagger-default-url: true
#    urls: []
#  api-docs:
#    path: /v3/api-docs
#    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false # activer sinon pour voir les endpoints actuator dans le swagger.
    
# http://localhost:1112/swagger-ui/index.html
app:
  openapi:
    local-url: http://${host.ip}:${server.port}
    dev-url: http://${host.ip}:${server.port}
    homol-url: http://${host.ip}:${server.port}
    prod-url: https://${host.ip}:${server.port}

## uri de gr-conf-swagger-aggregator
swagger:
  aggregator:
    cors:
      uri: ${aggregator.cors.uri}

eureka:
  instance:
    metadata-map:
      # Indique que ce microservice doit être inclus dans le swagger de 'gr-conf-swagger-aggregator'' (désactiver le sinon sinon).
      swagger.aggregator.enabled: ${aggregator.eureka.enabled}