
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${parms.oauth2.issuerUri}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO