aggregator.eureka.enabled: false
params.restTemplateConfiguration.enabled: false
swagger-params.enabled: false

spring:
  cloud:
    discovery:
      enabled: true		
  security:
    oauth2:
      client:
        registration:
          ms3:
            provider: sts-provider
            client-id: gr-ms3-resource
            client-secret: secret3
            scope: actuator.read
            client-name: gr-ms3-resource-registration
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
        provider:
          sts-provider:
            token-uri: ${params.oauth2.issuerUri}/oauth2/token
# java -jar fakesmtp-2.0.jar -p 2525
# https://threadminions.wordpress.com/2019/06/25/alert-with-spring-boot-admin-server/
#  mail:
#    host: localhost
#    port: 2525
#    protocol: smtp

# Spring Boot Admin Configuration
  boot:
    admin:
      discovery:
        ignored-services: springboot-conf-admin-server
      server:
        # To enable or disable admin server
        enabled: true
      # To set title of admin server
      ui:
        title: SpringBoot-Admin UI
      monitor:
        # Time interval in ms to update the status of applications with 
        # expired status-informations.
        status-interval: 15000
        # To set lifetime of status. 
        # The status won't be updated as long the last status isn't expired.
        status-lifetime: 15000
        # Default number of retries for failed requests.
        # retry is available only for GET requests.
        default-retries: 2
      # To set context path of admin server
      context-path: /
      routes:
        endpoints: info
#      notify:
#        mail:
#          to: jihed@gmail.com, chaabane@gmail.com
#          enabled: true

  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    driver-class-name: org.postgresql.Driver
    username: ${database.username}
    password: ${database.password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool_SBOOT_ADMIN
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
    show-sql: false