## uri/enabled de gr-conf-swagger-aggregator
aggregator.eureka.enabled: false

#server:
#  ssl:
#    trust-store: classpath:ms1-truststore.jks
#    trust-store-password: jihed1234
#javax:
#  net:
#    ssl:
#      trustStore: classpath:ms1-truststore.jks
#      trustStorePassword: jihed1234

spring:
# java -jar fakesmtp-2.0.jar -p 2525
# https://threadminions.wordpress.com/2019/06/25/alert-with-spring-boot-admin-server/
#  mail:
#    host: localhost
#    port: 2525
#    protocol: smtp

# Spring Boot Admin Configuration
  boot:
    admin:
      discovery:
        ignored-services: springboot-conf-admin-server
      server:
        # To enable or disable admin server
        enabled: true
      # To set title of admin server
      ui:
        title: SpringBoot-Admin UI
      monitor:
        # Time interval in ms to update the status of applications with 
        # expired status-informations.
        status-interval: 15000
        # To set lifetime of status. 
        # The status won't be updated as long the last status isn't expired.
        status-lifetime: 15000
        # Default number of retries for failed requests.
        # retry is available only for GET requests.
        default-retries: 2
      # To set context path of admin server
      context-path: /
      routes:
        endpoints: info
#      notify:
#        mail:
#          to: jihed@gmail.com, chaabane@gmail.com
#          enabled: true
