foo:
  msg: foo-default
  props:
    fooprop1: foo-default 1
    fooprop2: foo-default 2
    fooprop3: foo-default 3

spring:
  zipkin:
    base-url: ${params.zipkin.uri}
  sleuth:
    sampler:
      probability: 1.0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    # Activer le mode "try it out" pour tous les endpoints
    try-it-out-enabled: true
  show-actuator: false # activer sinon pour voir les endpoints actuator dans le swagger.