#local
host.where.docker.ip: localhost
# TODO to delete : issue @Bean public ProviderSettings providerSettings() {}
auth.server.issuerUri: http://${host.where.docker.ip}:8764

params:
  eureka:
    uri: http://localhost:8761/eureka/
  oauth2:
    issuerUri: http://SPRINGBOOT-CONF-STS-AUTHORIZATION-SERVER-DB
  gateway:
    uri: http://localhost:8766
  gatewayOauth2:
    uri: http://SPRINGBOOT-CONF-GATEWAY-API-OAUTH2
  zipkin:
    uri: http://localhost:9411
  keystore:
    type: PKCS12
    path: file:C:/E/TOOLS/ms2.p12
    password: jihed123
    alias: ms2
  truststore:
    path: C:/E/TOOLS/ms1-truststore.jks
    password: jihed1234