#local
host.where.docker.ip: localhost

params:
  oauth2:
    issuerUri: http://localhost:8764
  zipkin:
    uri: http://localhost:9411
  # URLs de l'API Gateway pour les appels aux microservices
  gateway:
    uri: http://localhost:7766