# prod
host.where.docker.ip: 10.0.0.600

params:
  oauth2:
    issuerUri: http://container-springboot-conf-sts-authorization-server-db:8764
  gateway:
    http://container-springboot-conf-gateway-api:8766
  gatewayOauth2:
    uri: http://container-springboot-conf-gateway-api-oauth2:7766
  zipkin:
    uri: http://container-zipkin:9411