#local
host.where.docker.ip: localhost

params:
  oauth2:
    issuerUri: http://localhost:8764
  gateway:
    http://localhost:8766
  gatewayOauth2:
    uri: http://localhost:7766
  zipkin:
    uri: http://localhost:9411