# prod
host.where.docker.ip: 10.0.0.600

params:
  eureka:
    uri: http://user:user@container-springboot-conf-eureka-server:8761/eureka/
  oauth2:
    issuerUri: http://container-springboot-conf-sts-authorization-server-db:8764
  gatewayOauth2:
    uri: http://SPRINGBOOT-CONF-GATEWAY-API-OAUTH2
  swaggerAggregator:
    uri: http://container-gr-conf-swagger-aggregator:8766
  zipkin:
    uri: http://container-zipkin:9411
    enabled: ${zipkin.enabled:false}
    probability: ${zipkin.sleuth.probability}
  keystore:
    type: PKCS12
    path: file:/certificates/ms2.p12
    password: jihed123
    alias: ms2
  truststore:
    path: /certificates/ms1-truststore.jks
    password: jihed1234