#local
host.where.docker.ip: localhost

params:
  eureka:
    uri: http://localhost:8761/eureka/
  oauth2:
    issuerUri: http://localhost:8764
    #----> for SPRINGBOOT-OAUTH2-EXTERNAL-RESTTEMPLATE-CONSUMER until: 
    #----> @TODO try to replace it with eureka discovery alternative.
    #----> .issuer("http://SPRINGBOOT-CONF-STS-AUTHORIZATION-SERVER-DB")
    loadBalancedIssuerUri: http://SPRINGBOOT-CONF-STS-AUTHORIZATION-SERVER-DB
  gateway:
    uri: http://localhost:8766
  gatewayOauth2:
    uri: http://SPRINGBOOT-CONF-GATEWAY-API-OAUTH2
  swaggerAggregator:
    uri: http://localhost:8765  # Didnot work : localhost, 192.168.56.1, GR-OAUTH2-SWAGGER-AGGREGATOR, GR-CONF-SWAGGER-AGGREGATOR
  zipkin:
    uri: http://localhost:9411
  keystore:
    type: PKCS12
    path: file:C:/E/TOOLS/ms2.p12
    password: jihed123
    alias: ms2
  truststore:
    path: C:/E/TOOLS/ms1-truststore.jks
    password: jihed1234