# homol
host.where.docker.ip: 10.0.0.500

params:
  eureka:
    uri: http://container-springboot-conf-eureka-server:8761/eureka/
  oauth2:
    issuerUri: http://SPRINGBOOT-CONF-STS-AUTHORIZATION-SERVER-DB
  gateway:
    uri: http://container-springboot-conf-gateway-api:8766
  gatewayOauth2:
    uri: http://SPRINGBOOT-CONF-GATEWAY-API-OAUTH2
  zipkin:
    uri: http://container-zipkin:9411
  keystore:
    type: PKCS12
    path: file:/certificates/ms2.p12
    password: jihed123
    alias: ms2
  truststore:
    path: /certificates/ms1-truststore.jks
    password: jihed1234