eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: ${eureka.fetch.seconds:25}
    service-url:
      defaultZone: ${params.eureka.uri}
  instance:
    preferIpAddress: true
    #----> Remove ipAddress and hostname to let Eureka resolve dynamically
    #ipAddress: ${host.where.docker.ip}
    #----> Optionally, set a non-qualified hostname if needed
    #hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.int}
    metadata-map:
      #----> Indique que ce microservice doit être inclus dans le swagger de 'gr-conf-swagger-aggregator'
      #----> (désactivé par défaut sinon).
      swagger.aggregator.enabled: ${aggregator.eureka.enabled:false}
      management.context-path: /actuator

management:
  endpoints:
    web.exposure.include: "*"
    web.base-path: /actuator
    web.enable.include: health
  endpoint:
    health:
      show-details: ALWAYS
  # --> Include git.properties generated informations (plugin:git-commit-id-plugin) in /actuator/info endpoint.
  info:
    git:
      mode: full

##----> START : uri de gr-conf-swagger-aggregator
swagger-params:
  issuerUri: ${params.oauth2.issuerUri}
  servers:
    liste:
      - uri: http://localhost:${server.port}
        description: Local environment
      - uri: http://10.0.0.137:${server.port}
        description: Development environment
      - uri: http://10.0.0.500:${server.port}
        description: Homologation environment
      - uri: http://10.0.0.600:${server.port}
        description: Production environment
  aggregator:
    enabled: ${aggregator.eureka.enabled:false}
    cors:
      uri: ${params.swaggerAggregator.uri}