# dev
host.where.docker.ip: 10.0.0.137

params:
  oauth2:
    issuerUri: http://container-springboot-conf-sts-authorization-server-db:8764
  zipkin:
    uri: http://container-zipkin:9411
  # URLs de l'API Gateway pour les appels aux microservices
  gateway:
    uri: http://container-springboot-conf-gateway-api-oauth2:7766