# dev
host.where.docker.ip: 10.0.0.137

params:
  eureka:
    uri: http://container-springboot-conf-eureka-server:8761/eureka/
  oauth2:
    issuerUri: http://container-springboot-conf-sts-authorization-server-db:8764
    #----> for SPRINGBOOT-OAUTH2-EXTERNAL-RESTTEMPLATE-CONSUMER until: 
    #----> @TODO try to replace it with eureka discovery alternative.
    #----> .issuer("http://SPRINGBOOT-CONF-STS-AUTHORIZATION-SERVER-DB")
    loadBalancedIssuerUri: http://SPRINGBOOT-CONF-STS-AUTHORIZATION-SERVER-DB
  gateway:
    uri: http://container-springboot-conf-gateway-api:8766
  gatewayOauth2:
    uri: http://SPRINGBOOT-CONF-GATEWAY-API-OAUTH2
  swaggerAggregator:
    uri: http://container-gr-conf-swagger-aggregator:8765
  zipkin:
    uri: http://container-zipkin:9411
  keystore:
    type: PKCS12
    path: file:/certificates/ms2.p12
    password: jihed123
    alias: ms2
  truststore:
    path: /certificates/ms1-truststore.jks
    password: jihed1234