
spring:
  zipkin:
    base-url: ${params.zipkin.uri}
  sleuth:
    sampler:
      probability: 1.0

# Configuration pour les appels à l'Authorization Server
authorization:
  server:
    url: ${params.oauth2.issuerUri}/oauth2/token
  ms1:
    clientId: ${params.oauth2.client1.clientId}
    clientSecret: ${params.oauth2.client1.clientSecret}
    scopes: ${params.oauth2.client1.scopes}
  ms2:
    clientId: ${params.oauth2.client2.clientId}
    clientSecret: ${params.oauth2.client2.clientSecret}
    scopes: ${params.oauth2.client2.scopes}

## START SWAGGER
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    # Activer le mode "try it out" pour tous les endpoints
    try-it-out-enabled: true
  show-actuator: false # activer sinon pour voir les endpoints actuator dans le swagger.
## END SWAGGER