
spring:
  zipkin:
    base-url: ${params.zipkin.uri}
  sleuth:
    sampler:
      probability: 1.0

# URLs de l'API Gateway pour les appels aux microservices
api:
  gateway:
    url: ${params.gateway.uri} 

# Configuration pour les appels à l'Authorization Server
authorization:
  server:
    url: ${params.oauth2.issuerUri}/oauth2/token
    ms1:
      client-id: ${params.oauth2.client1.clientId}
      client-secret: ${params.oauth2.client1.clientSecret}
      scope: ${params.oauth2.client1.scope}
    ms2:
      client-id: ${params.oauth2.client2.clientId}
      client-secret: ${params.oauth2.client2.clientId}
      scope: ${params.oauth2.client2.scope}

