spring:
  security:
    oauth2:
      client:
        registration:
          oauth2-products-resource-server-client-credentials:
            provider: spring
            client-id: ${caller.secured.client0.clientId}
            client-secret: ${caller.secured.client0.clientSecret}
            scope: ${caller.secured.client0.scopes}
            authorization-grant-type: client_credentials
            client-name: oauth2-products-resource-server-client-credentials
          oauth2-client1-resource-server-client-credentials:
            provider: spring
            client-id: ${caller.secured.client1.clientId}
            client-secret: ${caller.secured.client1.clientSecret}
            scope: ${caller.secured.client1.scopes}
            authorization-grant-type: client_credentials
            client-name: oauth2-client1-resource-server-client-credentials
          oauth2-client2-resource-server-client-credentials:
            provider: spring
            client-id: ${caller.secured.client2.clientId}
            client-secret: ${caller.secured.client2.clientSecret}
            scope: ${caller.secured.client2.scopes}
            authorization-grant-type: client_credentials
            client-name: oauth2-client2-resource-server-client-credentials
          oauth2-client3-resource-server-client-credentials:
            provider: spring
            client-id: ${caller.secured.client3.clientId}
            client-secret: ${caller.secured.client3.clientSecret}
            scope: ${caller.secured.client3.scopes}
            authorization-grant-type: client_credentials
            client-name: oauth2-client3-resource-server-client-credentials
        provider:
          spring:
            issuer-uri: ${params.oauth2.issuerUri}
  zipkin:
    base-url: ${params.zipkin.uri}
  sleuth:
    sampler:
      probability: 1.0

## START SWAGGER
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    # Activer le mode "try it out" pour tous les endpoints
    try-it-out-enabled: true
  show-actuator: false # activer sinon pour voir les endpoints actuator dans le swagger.
## END SWAGGER

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG