spring:
  security:
    oauth2:
      client:
        registration:
          sts-spring-boot-resource-server-read-write:
            provider: spring
            client-id: ${caller.secured.client0.clientId}
            client-secret: ${caller.secured.client0.clientSecret}
            scope: ${caller.secured.client0.scopes}
            client-name: ${caller.secured.client0.registrationId}
            authorization-grant-type: client_credentials
          sts-spring-boot-resource-server-read:
            provider: spring
            client-id: ${caller.secured.client00.clientId}
            client-secret: ${caller.secured.client00.clientSecret}
            scope: ${caller.secured.client00.scopes}
            client-name: ${caller.secured.client00.registrationId}
            authorization-grant-type: client_credentials
          sts-spring-boot-resource-server-write:
            provider: spring
            client-id: ${caller.secured.client01.clientId}
            client-secret: ${caller.secured.client01.clientSecret}
            scope: ${caller.secured.client01.scopes}
            client-name: ${caller.secured.client01.registrationId}
            authorization-grant-type: client_credentials
          sts-spring-boot-resource-server-none:
            provider: spring
            client-id: ${caller.secured.client02.clientId}
            client-secret: ${caller.secured.client02.clientSecret}
            scope: ${caller.secured.client02.scopes}
            client-name: ${caller.secured.client02.registrationId}
            authorization-grant-type: client_credentials


          oauth2-client1-resource-server:
            provider: spring
            client-id: ${caller.secured.client1.clientId}
            client-secret: ${caller.secured.client1.clientSecret}
            scope: ${caller.secured.client1.scopes}
            client-name: ${caller.secured.client1.registrationId}
            authorization-grant-type: client_credentials
          oauth2-client2-resource-server:
            provider: spring
            client-id: ${caller.secured.client2.clientId}
            client-secret: ${caller.secured.client2.clientSecret}
            scope: ${caller.secured.client2.scopes}
            client-name: ${caller.secured.client2.registrationId}
            authorization-grant-type: client_credentials
          oauth2-client3-resource-server:
            provider: spring
            client-id: ${caller.secured.client3.clientId}
            client-secret: ${caller.secured.client3.clientSecret}
            scope: ${caller.secured.client3.scopes}
            client-name: ${caller.secured.client3.registrationId}
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: ${params.oauth2.issuerUri}
  zipkin:
    base-url: ${params.zipkin.uri}
  sleuth:
    sampler:
      probability: 1.0

## START SWAGGER
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    # Activer le mode "try it out" pour tous les endpoints
    try-it-out-enabled: true
  show-actuator: false # activer sinon pour voir les endpoints actuator dans le swagger.
## END SWAGGER

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG