aggregator.eureka.enabled: true
params.restTemplateConfiguration.enabled: false
swagger-params.enabled: true

zipkin.enabled: true
zipkin.sleuth.probability: 1.0

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${params.oauth2.issuerUri}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO