spring:
  cloud:
    discovery:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${params.oauth2.issuerUri}

zipkin.enabled: true
zipkin.sleuth.probability: 1.0