hello:
  msg: hello-default
  props:
    helloprop1: hello-default 1
    helloprop2: hello-default 2
    helloprop3: hello-default 3

aggregator.eureka.enabled: true
params.restTemplateConfiguration.enabled: false
swagger-params.enabled: true

spring:
  zipkin:
    base-url: ${params.zipkin.uri}
  sleuth:
    sampler:
      probability: 1.0