spring:
  security:
    oauth2:
      client:
        registration:
          sts-oauth2-client2-resource-server-registration:
            provider: sts-provider
            client-id: ${caller.destination.client1.clientId}
            client-secret: ${caller.destination.client1.clientSecret}
            scope: ${caller.destination.client1.scopes}
            client-name: ${caller.destination.client1.registrationId}
            authorization-grant-type: client_credentials
        provider:
          sts-provider:
            token-uri: ${params.oauth2.issuerUri}/oauth2/token
            # Explicitly disable user-info and authorization endpoints (not used in client_credentials)
            authorization-uri: ${params.oauth2.issuerUri}/oauth2/authorize
            #user-info-uri: ${params.oauth2.issuerUri}/userinfo
      resourceserver:
        jwt:
          issuer-uri: ${params.oauth2.issuerUri}
          #issuer-uri: ${auth.server.issuerUri}

  zipkin:
    base-url: ${params.zipkin.uri}
  sleuth:
    sampler:
      probability: 1.0

## START SWAGGER
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    # Activer le mode "try it out" pour tous les endpoints
    try-it-out-enabled: true
  show-actuator: false # activer sinon pour voir les endpoints actuator dans le swagger.
## END SWAGGER