spring:
  cloud:
    discovery:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          consumer-webclient:
            provider: sts-provider
            client-id: gr-resource-consumer-webclient
            client-secret: consumer-webclient
            scope: ms1.read,ms2.read,ms3.read
            client-name: gr-resource-consumer-webclient-registration
            authorization-grant-type: client_credentials
        provider:
          sts-provider:
            token-uri: ${params.oauth2.issuerUri}/oauth2/token

zipkin.enabled: true
zipkin.sleuth.probability: 1.0