spring:
  security:
    oauth2:
      authorizationserver:
        issuer: ${params.oauth2.issuerUri}
        #issuer: ${auth.server.issuerUri}
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    driver-class-name: org.postgresql.Driver
    username: ${database.username}
    password: ${database.password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool_STS_AUTH_SERVER_DB
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
      show-sql: false
      
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO