spring:
  cloud:
    gateway:
      #discovery:
        #locator:
          #enabled: true
          #lower-case-service-id: true
      routes:
        - id: GR-SPRINGBOOT-SWAGGER-OPENAPI-SQUELETON
          uri: http://10.0.0.137:1112
          predicates:
            - Path=/squeleton/get/**, /squeleton/post/**
        - id: Z-SPRINGBOOT-FOO-SERVICE
          uri: http://10.0.0.137:7778
          predicates:
            - Path=/foo/**
        - id: Z-SPRINGBOOT-BAR-SERVICE
          uri: http://10.0.0.137:7777
          predicates:
            - Path=/bar/**
        - id: Z-SPRINGBOOT-HELLO
          uri: http://10.0.0.137:7775
          predicates:
            - Path=/hello/**
        - id: Z-SPRINGBOOT-HELLO-WORLD-SERVICE
          uri: http://10.0.0.137:7775
          predicates:
            - Path=/helloservice/**


