aggregator.eureka.enabled: true
params.restTemplateConfiguration.enabled: false
swagger-params.enabled: true

springdoc:
  swagger-ui:
    oauth:
      clientId: gr-oauth2-swagger-ms2
      clientSecret: swagger-ms2

caller:
  destination:
    # gr-oauth2-swagger-ms2 from swagger.
    client0:
      resourceUri:
      clientId: gr-oauth2-swagger-ms2
      clientSecret: swagger-ms2
      scopes: update,remove
      registrationId: gr-oauth2-swagger-ms2