aggregator.eureka.enabled: true
params.restTemplateConfiguration.enabled: false
swagger-params.enabled: true

zipkin.enabled: true
zipkin.sleuth.probability: 1.0

spring:
  security:
    oauth2:
      client:
        registration:
          sts-oauth2-products-resource-registration:
            provider: sts-provider
            client-id: ${caller.destination.client1.clientId}
            client-secret: ${caller.destination.client1.clientSecret}
            scope: ${caller.destination.client1.scopes}
            client-name: ${caller.destination.client1.registrationId}
            authorization-grant-type: client_credentials
          sts-oauth2-client1-resource-server-registration:
            provider: sts-provider
            client-id: ${caller.destination.client2.clientId}
            client-secret: ${caller.destination.client2.clientSecret}
            scope: ${caller.destination.client2.scopes}
            client-name: ${caller.destination.client2.registrationId}
            authorization-grant-type: client_credentials
          sts-oauth2-client2-resource-server-registration:
            provider: sts-provider
            client-id: ${caller.destination.client3.clientId}
            client-secret: ${caller.destination.client3.clientSecret}
            scope: ${caller.destination.client3.scopes}
            client-name: ${caller.destination.client3.registrationId}
            authorization-grant-type: client_credentials
        provider:
          sts-provider:
            issuer-uri: ${params.oauth2.issuerUri}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG