caller:
  destination:
    # gr-oauth2-swagger-aggregator from swagger.
    client0:
      resourceUri:
      clientId:
      clientSecret:
      scopes:
      registrationId:

eureka.fetch.seconds: 30
aggregator.eureka.enabled: true