spring:
  cloud:
    discovery:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          ms1:
            provider: sts-provider
            client-id: ${caller.destination.client0.clientId}
            client-secret: ${caller.destination.client0.clientSecret}
            scope: ${caller.destination.client0.scopes}
            client-name: ${caller.destination.client0.registrationId}
            authorization-grant-type: client_credentials
        provider:
          sts-provider:
            token-uri: ${params.oauth2.issuerUri}/oauth2/token
      resourceserver:
        jwt:
          issuer-uri: ${params.oauth2.issuerUri}

  zipkin:
    base-url: ${params.zipkin.uri}
  sleuth:
    sampler:
      probability: 1.0